// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYVwBC4acTUlJ_7mCiCQpxv0krvFQTHbQ',
    appId: '1:892445082720:web:96eb1b4e9f2adae3ca2f05',
    messagingSenderId: '892445082720',
    projectId: 'workzen-72a11',
    authDomain: 'workzen-72a11.firebaseapp.com',
    storageBucket: 'workzen-72a11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5hP-l0FuXFWMkOe-bMmahVqqJ_KBpa5s',
    appId: '1:892445082720:android:53845a1750dbb75eca2f05',
    messagingSenderId: '892445082720',
    projectId: 'workzen-72a11',
    storageBucket: 'workzen-72a11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoWy59vIGER8coyrV7rm0eRqHskz_4th4',
    appId: '1:892445082720:ios:d38524ee7d86984cca2f05',
    messagingSenderId: '892445082720',
    projectId: 'workzen-72a11',
    storageBucket: 'workzen-72a11.firebasestorage.app',
    iosBundleId: 'com.example.workzen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoWy59vIGER8coyrV7rm0eRqHskz_4th4',
    appId: '1:892445082720:ios:d38524ee7d86984cca2f05',
    messagingSenderId: '892445082720',
    projectId: 'workzen-72a11',
    storageBucket: 'workzen-72a11.firebasestorage.app',
    iosBundleId: 'com.example.workzen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYVwBC4acTUlJ_7mCiCQpxv0krvFQTHbQ',
    appId: '1:892445082720:web:7475fe7023b12814ca2f05',
    messagingSenderId: '892445082720',
    projectId: 'workzen-72a11',
    authDomain: 'workzen-72a11.firebaseapp.com',
    storageBucket: 'workzen-72a11.firebasestorage.app',
  );
}
